import { POI } from "./POI";

export let poi: Array<POI> = [
    {
        firstName: "Jones",
        dob:'12-Sep-1999',
        contactNumber:'0717159998',
        surname: "Mashilo",
        idNumber: 123456789012,
        offence: "Offence 3",
        status: false,
        image: "https://cdn.auth0.com/blog/whatabyte/burger-sm.png",
        currentAddressId:'1',
        Branch:'Marabastad',
        homeAddressId:"1",
        dateOfBaptism:"11-Jul-2018",
        tiktok:'jonesses',
        facebook:'',
        instagram:'',
        occupation:'hustler',
        father:'',
        mother:'',
        siblings:[]
    },
    {
        firstName: "Tom",
        dob:'12-Sep-1999',
        contactNumber:'0717159998',
        surname: "Ford",
        idNumber: 123456789013,
        offence: "Offence 2",
        status: false,
        image: "https://cdn.auth0.com/blog/whatabyte/pizza-sm.png",
        currentAddressId:'1',
        Branch:'Marabastad',
        homeAddressId:"1",
        dateOfBaptism:"11-Jul-2018",
        tiktok:'jonesses',
        facebook:'',
        instagram:'',
        occupation:'hustler',
        father:'',
        mother:'',
        siblings:[]
    },
    {
        firstName: "Alexa",
        dob:'12-Sep-1999',
        contactNumber:'0717159998',
        surname: "Google",
        idNumber: 123456789014,
        offence: "Offence 1",
        status: true,
        image: "https://cdn.auth0.com/blog/whatabyte/tea-sm.png",
        currentAddressId:'1',
        Branch:'Marabastad',
        homeAddressId:"1",
        dateOfBaptism:"11-Jul-2018",
        tiktok:'jonesses',
        facebook:'',
        instagram:'',
        occupation:'hustler',
        father:'',
        mother:'',
        siblings:[]
    }
]